kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: intuitive-fermi-5195795de1-scaler
  namespace: apps-dev
spec:
  hosts:
    - cc1fbde45ead-in-south-01.mayson.dev
  pathPrefixes:
    - /us-east-1-backstractelb-17828a-coll-8988b194455245ab92ba9aff8b6a795a/ # e.g. /infallible-naveen-... intuitive-fermi-5195795de1/
  scaleTargetRef:
    name: intuitive-fermi-5195795de1-depl
    kind: Deployment
    apiVersion: apps/v1
    service: intuitive-fermi-5195795de1-srv # e.g. coll-8a2a...-srv
    port: 80
  replicas:
    min: 0
    max: 10
  scaledownPeriod: 604800 #inseconds
  scalingMetric:
    requestRate:
      targetValue: 100
      window: 1m